// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace APIApp
{
    public partial class ConversionUnit
    {
        public ConversionUnit()
        {
            EmissionItem = new HashSet<EmissionItem>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string UnitName { get; set; }

        [InverseProperty("ConversionUnit")]
        public virtual ICollection<EmissionItem> EmissionItem { get; set; }
    }
}