// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace APIApp
{
    public partial class EmissionItem
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string ItemName { get; set; }
        [StringLength(100)]
        public string CarbonCoefficient { get; set; }
        public int? ConversionUnitID { get; set; }
        [StringLength(100)]
        public string Remarks { get; set; }
        [StringLength(100)]
        public string DQI { get; set; }
        [StringLength(100)]
        public string DataSource { get; set; }
        [Column(TypeName = "datetime")]
        
        public DateTime? DataSourceDate { get; set; }
        public bool? IsActive { get; set; }
        public int? CategoryId { get; set; }
        public int? SubCategoryId { get; set; }
        public int? SubSubCategoryId { get; set; }

        [ForeignKey(nameof(ConversionUnitID))]
        [InverseProperty("EmissionItem")]
        public virtual ConversionUnit ConversionUnit { get; set; }
    }
}